// Translation object for English and Spanish UI elements
const translations = {
    en: {
        cvBuilder: "CV Builder",
        personalInformation: "Personal Information",
        name: "Name",
        title: "Title",
        email: "Email",
        phone: "Phone",
        linkedin: "LinkedIn",
        github: "GitHub",
        website: "Website",
        address: "Address",
        profilePicture: "Profile Picture",
        profileFrameColor: "Profile Frame Color",
        uploadImage: "Upload Image",
        removeImage: "Remove Image",
        summary: "Summary",
        summaryPlaceholder: "A brief overview of your professional background and goals.",
        workExperience: "Work Experience",
        addExperience: "Add Experience",
        removeExperience: "Remove Experience",
        jobTitle: "Title",
        company: "Company",
        location: "Location",
        startDate: "Start Date",
        endDate: "End Date",
        present: "Present",
        responsibilitiesAchievements: "Responsibilities/Achievements",
        responsibilitiesAchievementsPlaceholder: "Describe responsibilities and measurable achievements.",
        addDescriptionLine: "Add Description Line",
        removeLine: "Remove line",
        education: "Education",
        addEducation: "Add Education",
        removeEducation: "Remove Education",
        degree: "Degree",
        university: "University",
        year: "Year",
        detailsOptional: "Details (Optional)",
        detailsPlaceholder: "e.g., Graduated with honors, Relevant coursework...",
        skills: "Skills",
        programmingLanguages: "Programming Languages",
        frameworks: "Frameworks",
        databases: "Databases",
        tools: "Tools",
        addSkill: "Add Skill",
        removeSkill: "Remove skill",
        addSkillCategory: "Add Skill Category",
        removeSkillCategory: "Remove Category",
        skillCategoryName: "Category Name",
        skillCategoryNamePlaceholder: "e.g., Cloud Platforms",
        projects: "Projects",
        addProject: "Add Project",
        removeProject: "Remove Project",
        projectName: "Project Name",
        technologiesUsed: "Technologies Used",
        projectDescription: "Description",
        projectDescriptionPlaceholder: "Brief description of the project and your role.",
        linkOptional: "Link (Optional)",
        awardsCertifications: "Courses & Certifications",
        addAwardCertification: "Add Course/Certification",
        removeAward: "Remove Course/Certification",
        customSections: "Custom Sections",
        addCustomSection: "Add Section",
        removeCustomSection: "Remove Section",
        customSectionTitle: "Section Title",
        customSectionTitlePlaceholder: "e.g., Publications",
        customSectionItemPlaceholder: "Section item",
        awardName: "Name",
        awardYear: "Year",
        awardDescriptionOptional: "Description (Optional)",
        awardDescriptionPlaceholder: "e.g., Certification in...",
        exportToPdf: "Export to PDF",
        exportToPdfText: "Export PDF (Text)",
        exportToPdfImage: "Export PDF (Image)",
        exportCvSession: "Export CV Data File",
        importCvSession: "Import CV Data File",
        cvPreview: "CV Preview",
        saveSuccess: "CV data saved to file successfully!",
        saveError: "Error saving CV data to file. Please try again.",
        loadSuccess: "CV data loaded from file successfully!",
        loadPartial: "CV data loaded with adjustments:",
        loadError: "Error loading CV data from file. The file might be corrupted or invalid.",
        noFileSelected: "No file selected.",
        language: "Language",
        english: "English",
        spanish: "Spanish",
        newSession: "New Session",
        newSessionConfirm: "Are you sure you want to start a new session? All unsaved data will be lost.",
        newSessionStarted: "New session started. All data cleared.",
        pdfExportFallback: "Text PDF export failed, using image-based fallback.",
        versions: "Versions",
        newVersion: "New Version",
        versionFilters: "Version filters",
        active: "Active",
        versionFocus: "Version focus",
        primaryFocus: "Primary focus",
        secondaryFocuses: "Secondary focuses",
        industry: "Industry",
        visibleExperienceItems: "Visible experience items",
        visibleProjectItems: "Visible project items",
        skillCategoriesAndItems: "Skill categories and items",
        show: "Show",
        hide: "Hide",
        showAll: "Show all",
        hideAll: "Hide all",
        visible: "Visible",
        hidden: "Hidden",
        moveEarlier: "Move earlier",
        moveLater: "Move later",
        noExperienceItemsInVersion: "No experience items in this version.",
        noProjectItemsInVersion: "No project items in this version.",
        noSkillsInCategory: "No skills in this category.",
        versionLocalAdditions: "Version-local additions",
        pendingSkills: "Pending skills",
        pendingSections: "Pending sections",
        addToMaster: "Add to master",
        skillCategory: "Skill category",
        newSkill: "New skill",
        newSectionTitle: "New section title",
        addSkillVersion: "Add skill",
        addSectionVersion: "Add section",
        renameVersion: "Rename version",
        duplicateVersion: "Duplicate version",
        deleteVersion: "Delete version",
        newVersionCreated: "New version created",
        versionDuplicated: "Version duplicated",
        versionDeleted: "Version deleted",
        atLeastOneVersion: "At least one version is required",
        versionRenamePrompt: "Rename version",
        versionDeleteConfirm: "Delete this version?",
        projectBundleImported: "Project bundle imported successfully",
        projectBundleImportFailed: "Project bundle import failed",
        versionName: "Version name",
    },
    es: {
        cvBuilder: "Constructor de CV",
        personalInformation: "Información Personal",
        name: "Nombre",
        title: "Título",
        email: "Correo Electrónico",
        phone: "Teléfono",
        linkedin: "LinkedIn",
        github: "GitHub",
        website: "Sitio Web",
        address: "Dirección",
        profilePicture: "Foto de Perfil",
        profileFrameColor: "Color del Marco de la Foto",
        uploadImage: "Subir Imagen",
        removeImage: "Eliminar Imagen",
        summary: "Resumen",
        summaryPlaceholder: "Una breve descripción de su experiencia profesional y objetivos.",
        workExperience: "Experiencia Laboral",
        addExperience: "Añadir Experiencia",
        removeExperience: "Eliminar Experiencia",
        jobTitle: "Puesto",
        company: "Empresa",
        location: "Ubicación",
        startDate: "Fecha de Inicio",
        endDate: "Fecha de Fin",
        present: "Actualidad",
        responsibilitiesAchievements: "Responsabilidades/Logros",
        responsibilitiesAchievementsPlaceholder: "Describa responsabilidades y logros medibles.",
        addDescriptionLine: "Añadir Línea de Descripción",
        removeLine: "Eliminar línea",
        education: "Educación",
        addEducation: "Añadir Educación",
        removeEducation: "Eliminar Educación",
        degree: "Título",
        university: "Universidad",
        year: "Año",
        detailsOptional: "Detalles (Opcional)",
        detailsPlaceholder: "Ej: Graduado con honores, Cursos relevantes...",
        skills: "Habilidades",
        programmingLanguages: "Lenguajes de Programación",
        frameworks: "Frameworks",
        databases: "Bases de Datos",
        tools: "Herramientas",
        addSkill: "Añadir Habilidad",
        removeSkill: "Eliminar habilidad",
        addSkillCategory: "Añadir Categoría de Habilidades",
        removeSkillCategory: "Eliminar Categoría",
        skillCategoryName: "Nombre de la Categoría",
        skillCategoryNamePlaceholder: "Ej: Plataformas en la Nube",
        projects: "Proyectos",
        addProject: "Añadir Proyecto",
        removeProject: "Eliminar Proyecto",
        projectName: "Nombre del Proyecto",
        technologiesUsed: "Tecnologías Utilizadas",
        projectDescription: "Descripción",
        projectDescriptionPlaceholder: "Breve descripción del proyecto y su rol.",
        linkOptional: "Enlace (Opcional)",
        awardsCertifications: "Cursos y Certificaciones",
        addAwardCertification: "Añadir Curso/Certificación",
        removeAward: "Eliminar Curso/Certificación",
        customSections: "Secciones Personalizadas",
        addCustomSection: "Añadir Sección",
        removeCustomSection: "Eliminar Sección",
        customSectionTitle: "Título de la Sección",
        customSectionTitlePlaceholder: "Ej: Publicaciones",
        customSectionItemPlaceholder: "Elemento de la sección",
        awardName: "Nombre",
        awardYear: "Año",
        awardDescriptionOptional: "Descripción (Opcional)",
        awardDescriptionPlaceholder: "Ej: Curso de desarrollo en...",
        exportToPdf: "Exportar a PDF",
        exportToPdfText: "Exportar PDF (Texto)",
        exportToPdfImage: "Exportar PDF (Imagen)",
        exportCvSession: "Exportar Archivo de Datos CV",
        importCvSession: "Importar Archivo de Datos CV",
        cvPreview: "Vista Previa del CV",
        saveSuccess: "¡Datos del CV guardados en archivo correctamente!",
        saveError: "Error al guardar los datos del CV en archivo. Inténtelo de nuevo.",
        loadSuccess: "¡Datos del CV cargados desde archivo correctamente!",
        loadPartial: "Datos del CV cargados con ajustes:",
        loadError: "Error al cargar los datos del CV desde archivo. El archivo podría estar corrupto o no válido.",
        noFileSelected: "Ningún archivo seleccionado.",
        language: "Idioma",
        english: "Inglés",
        spanish: "Español",
        newSession: "Nueva Sesión",
        newSessionConfirm: "¿Está seguro de que desea iniciar una nueva sesión? Se perderán todos los datos no guardados.",
        newSessionStarted: "Nueva sesión iniciada. Todos los datos borrados.",
        pdfExportFallback: "La exportación de texto falló, usando respaldo basado en imagen.",
        versions: "Versiones",
        newVersion: "Nueva versión",
        versionFilters: "Filtros de versión",
        active: "Activa",
        versionFocus: "Enfoque de la versión",
        primaryFocus: "Enfoque principal",
        secondaryFocuses: "Enfoques secundarios",
        industry: "Industria",
        visibleExperienceItems: "Experiencias visibles",
        visibleProjectItems: "Proyectos visibles",
        skillCategoriesAndItems: "Categorías e habilidades",
        show: "Mostrar",
        hide: "Ocultar",
        showAll: "Mostrar todo",
        hideAll: "Ocultar todo",
        visible: "Visible",
        hidden: "Oculto",
        moveEarlier: "Mover antes",
        moveLater: "Mover después",
        noExperienceItemsInVersion: "No hay experiencias en esta versión.",
        noProjectItemsInVersion: "No hay proyectos en esta versión.",
        noSkillsInCategory: "No hay habilidades en esta categoría.",
        versionLocalAdditions: "Añadidos locales de la versión",
        pendingSkills: "Habilidades pendientes",
        pendingSections: "Secciones pendientes",
        addToMaster: "Añadir al maestro",
        skillCategory: "Categoría de habilidad",
        newSkill: "Nueva habilidad",
        newSectionTitle: "Nuevo título de sección",
        addSkillVersion: "Añadir habilidad",
        addSectionVersion: "Añadir sección",
        renameVersion: "Renombrar versión",
        duplicateVersion: "Duplicar versión",
        deleteVersion: "Eliminar versión",
        newVersionCreated: "Nueva versión creada",
        versionDuplicated: "Versión duplicada",
        versionDeleted: "Versión eliminada",
        atLeastOneVersion: "Se requiere al menos una versión.",
        versionRenamePrompt: "Renombrar versión",
        versionDeleteConfirm: "¿Eliminar esta versión?",
        projectBundleImported: "Se importó el paquete del proyecto correctamente",
        projectBundleImportFailed: "La importación del paquete del proyecto falló",
        versionName: "Nombre de la versión",
    },
};

// Initial state for all CV data fields, structured by locale

// Initial state for all CV data fields, structured by locale
const initialCvDataByLocale = {
    en: {
        personalInfo: {
            name: 'John Doe',
            title: 'Software Engineer',
            email: 'john.doe@example.com',
            phone: '123-456-7890',
            linkedin: 'linkedin.com/in/johndoe',
            github: 'github.com/johndoe',
            website: 'johndoe.com',
            address: 'Anytown, USA',
            profilePicture: 'https://placehold.co/150x150/aabbcc/ffffff?text=JD', // Placeholder image
            profileFrameColor: '#bfdbfe',
            profilePictureWidth: 150, // Initial placeholder dimensions
            profilePictureHeight: 150, // Initial placeholder dimensions
        },
        summary: 'Highly motivated and results-oriented software engineer with 5+ years of experience in developing robust and scalable web applications. Proficient in JavaScript, React, Node.js, and various database technologies. Seeking to leverage my skills to contribute to innovative projects.',
        experiences: [
            { id: 1, title: 'Senior Software Engineer', company: 'Tech Solutions Inc.', location: 'New York, NY', startDate: 'Jan 2022', endDate: 'Present', description: ['Led the development of a new microservices architecture, improving system scalability by 30%.', 'Implemented a real-time data processing pipeline using Kafka, reducing latency by 50%.', 'Mentored junior developers and conducted code reviews, ensuring high code quality.'] },
            { id: 2, title: 'Software Developer', company: 'Innovate Corp.', location: 'San Francisco, CA', startDate: 'Aug 2019', endDate: 'Dec 2021', description: ['Developed and maintained front-end components using React and Redux.', 'Collaborated with product managers to translate requirements into technical specifications.', 'Optimized database queries, leading to a 20% improvement in application performance.'] },
        ],
        education: [
            { id: 1, degree: 'M.S. in Computer Science', university: 'State University', location: 'Anytown, USA', year: '2019', details: 'Specialization in Artificial Intelligence and Machine Learning.' },
            { id: 2, degree: 'B.S. in Software Engineering', university: 'City College', location: 'Anytown, USA', year: '2017', details: 'Graduated with honors.' },
        ],
        skills: { programmingLanguages: ['JavaScript', 'Python', 'Java', 'C++'], frameworks: ['React', 'Node.js', 'Express.js', 'Django', 'Spring Boot'], databases: ['MongoDB', 'PostgreSQL', 'MySQL'], tools: ['Git', 'Docker', 'Kubernetes', 'Jira', 'AWS'] },
        projects: [
            { id: 1, name: 'E-commerce Platform', technologies: 'React, Node.js, MongoDB, Stripe API', description: 'Developed a full-stack e-commerce platform with user authentication, product catalog, shopping cart, and payment gateway integration.', link: 'github.com/johndoe/ecommerce-platform' },
        ],
        awards: [
            { id: 1, name: 'Dean\'s List', year: '2015, 2016, 2017', description: 'Recognized for outstanding academic achievement.' },
        ],
        customSections: [],
    },
    es: {
        personalInfo: {
            name: 'Juan Pérez',
            title: 'Ingeniero de Software',
            email: 'juan.perez@ejemplo.com',
            phone: '123-456-7890',
            linkedin: 'linkedin.com/in/juanperez',
            github: 'github.com/juanperez',
            website: 'juanperez.com',
            address: 'Cualquier ciudad, México',
            profilePicture: 'https://placehold.co/150x150/aabbcc/ffffff?text=JP',
            profileFrameColor: '#bfdbfe',
            profilePictureWidth: 150,
            profilePictureHeight: 150,
        },
        summary: 'Ingeniero de software altamente motivado y orientado a resultados con más de 5 años de experiencia en el desarrollo de aplicaciones web robustas y escalables. Dominio de JavaScript, React, Node.js y diversas tecnologías de bases de datos. Busco aprovechar mis habilidades para contribuir a proyectos innovadores.',
        experiences: [
            {
                id: 1,
                title: 'Ingeniero de Software Senior',
                company: 'Soluciones Tecnológicas Inc.',
                location: 'Nueva York, NY',
                startDate: 'Ene 2022',
                endDate: 'Actualidad',
                description: [
                    'Lideré el desarrollo de una nueva arquitectura de microservicios, mejorando la escalabilidad del sistema en un 30%.',
                    'Implementé un pipeline de procesamiento de datos en tiempo real usando Kafka, reduciendo la latencia en un 50%.',
                    'Mentoricé a desarrolladores junior y realicé revisiones de código, garantizando una alta calidad del mismo.'
                ]
            },
            {
                id: 2,
                title: 'Desarrollador de Software',
                company: 'Innovate Corp.',
                location: 'San Francisco, CA',
                startDate: 'Ago 2019',
                endDate: 'Dic 2021',
                description: [
                    'Desarrollé y mantuve componentes de front-end utilizando React y Redux.',
                    'Colaboré con gerentes de producto para traducir requisitos en especificaciones técnicas.',
                    'Optimicé consultas de bases de datos, lo que resultó en una mejora del 20% en el rendimiento de la aplicación.'
                ]
            },
        ],
        education: [
            {
                id: 1,
                degree: 'M.S. en Ciencias de la Computación',
                university: 'Universidad Estatal',
                location: 'Cualquier ciudad, México',
                year: '2019',
                details: 'Especialización en Inteligencia Artificial y Aprendizaje Automático.'
            },
            {
                id: 2,
                degree: 'B.S. en Ingeniería de Software',
                university: 'Colegio de la Ciudad',
                location: 'Cualquier ciudad, México',
                year: '2017',
                details: 'Graduado con honores.'
            },
        ],
        skills: {
            programmingLanguages: ['JavaScript', 'Python', 'Java', 'C++'],
            frameworks: ['React', 'Node.js', 'Express.js', 'Django', 'Spring Boot'],
            databases: ['MongoDB', 'PostgreSQL', 'MySQL'],
            tools: ['Git', 'Docker', 'Kubernetes', 'Jira', 'AWS'],
        },
        projects: [
            {
                id: 1,
                name: 'Plataforma de Comercio Electrónico',
                technologies: 'React, Node.js, MongoDB, API de Stripe',
                description: 'Desarrollé una plataforma de comercio electrónico full-stack con autenticación de usuarios, catálogo de productos, carrito de compras e integración de pasarela de pago.',
                link: 'github.com/juanperez/ecommerce-platform'
            },
        ],
        awards: [
            {
                id: 1,
                name: 'Lista del Decano',
                year: '2015, 2016, 2017',
                description: 'Reconocido por logros académicos sobresalientes.'
            },
        ],
        customSections: [],
    }
};


